### ISSUE TITLE
1.1 Research Motivation

### ISSUE THREAD

**Issue by Lisa-Holling** [course-dprep/airbnb-amenities-for-digital-nomads-barcelona#1]
Write and refine research motivation

1.1 Research motivation (10%)
The research question is clearly articulated and important. The choice for the research method (e.g., regression analysis) is motivated well. The way of deployment (e.g., PDF report, dashboard, …) is useful and accessible to potential knowledge users, and clearly communicates the conclusions of the analysis. The automated and reproducible workflow is of potential use to other students and the larger scientific community.

**Comment by lisaholling013** [comment]
Een kleinere dataset maken; bijvoorbeeld: appartementen in de Pijp in Amsterdam met 1 slaapkamer, 1 badkamer, 1 keuken etc. (dus bepaalde karaktereigenschappen van het appartement zelf);
Kijken welke andere factoren invloed hebben op de prijs: 
- aantal reviews
- gecertificeerde host
- etc.

**Comment by lisaholling013** [comment]
Een kleinere dataset maken; bijvoorbeeld: appartementen in de Pijp in Amsterdam met 1 slaapkamer, 1 badkamer, 1 keuken etc. (dus bepaalde karaktereigenschappen van het appartement zelf);
Kijken welke andere faciliteiten in het appartement invloed hebben op de prijs: 
- wasmachine
- haardroger
- tv/wifi
- etc. 

Motivatie: welke faciliteiten moet je als AirBnb host in je appartement aanschaffen om een hogere prijs te kunnen vragen?

**Comment by lisaholling013** [comment]
Kijken naar de invloed van evenementen (bijvoorbeeld Olympische spelen of WK) op de prijs van appartementen
