### ISSUE TITLE
work on research motivation

### ISSUE THREAD

**Issue by Lisa-Holling** [course-dprep/airbnb-amenities-for-digital-nomads-barcelona#8]
__Deliverable__
- write a short paragraph about our research question and the variables we will use in our research
- see bullet points in `ReadMe` and project description of "Research Motivation"

**Comment by maxbaaten** [comment]
In a city such as Barcelona there are many people who want to rent a room for a longer period. The question is how owners can entice these people to rent their apartments. People who want to stay in an Airbnb for an extended period may be looking for a room with extra amenities such as a washing machine or a coffee machine. Employees from certain companies who have to work for a couple of weeks in Barcelona might need some extra work space and/or WiFi for example.
